server:
  port: 8080

spring:
  application:
    name: saga-coordinator

  datasource:
    url: jdbc:postgresql://localhost:5432/transferdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.amqp: INFO
    org.hibernate.SQL: DEBUG
